version: '3.8'

services:
  # --- Web Server ---
  nginx:
    volumes:
      # -- CUSTOM VOLUMES START --
      # -- CUSTOM VOLUMES END --

      # Keep the default mount if you still want to use the www folder
      - ${PROJECTS_ROOT}:/var/www:delegated

  # --- PHP Services ---
  # IMPORTANT: You must map the same volumes to PHP containers so they can execute the code!
  
  php85:
    volumes:
      # -- CUSTOM VOLUMES START --
      # -- CUSTOM VOLUMES END --
      - ${PROJECTS_ROOT}:/var/www:delegated

  php82:
    volumes:
      # -- CUSTOM VOLUMES START --
      # -- CUSTOM VOLUMES END --
      - ${PROJECTS_ROOT}:/var/www:delegated

  php74:
    volumes:
      # -- CUSTOM VOLUMES START --
      # -- CUSTOM VOLUMES END --
      - ${PROJECTS_ROOT}:/var/www:delegated
